"""
ISP IP Address Monitor.

Tracks the local machine's public (ISP) IP address and detects changes.
Stores last known IP in data/ip_state.json. Alerts are generated by the
caller (pipeline) via send_text() when a change is detected.

Hardened fallback chain supports JSON & plain-text IPv4 providers with
regex extraction and public IPv4 validation.
"""

from __future__ import annotations

import json
import logging
import re
import time
import urllib.request
from pathlib import Path

from config.settings import DATA_DIR

log = logging.getLogger(__name__)

IP_STATE_PATH = DATA_DIR / "ip_state.json"

# Ordered list of IP detection URLs (primary → fallback).
_IP_PROVIDERS = [
    "https://api4.ipify.org?format=json",
    "https://ipv4.icanhazip.com",
    "https://ipinfo.io/json",
    "https://api.ipify.org?format=json",
    "https://ifconfig.me/ip",
]

_HTTP_TIMEOUT = 10  # seconds per request
_IPV4_REGEX = re.compile(r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b")


def _is_valid_public_ipv4(ip: str) -> bool:
    """Validate that ip is a valid public IPv4 address (not private/loopback)."""
    if not ip or not isinstance(ip, str):
        return False
    parts = ip.split(".")
    if len(parts) != 4:
        return False
    try:
        octets = [int(p) for p in parts]
    except ValueError:
        return False

    o1, o2 = octets[0], octets[1]
    # Filter loopback, link-local, broadcast, private ranges
    if o1 == 0 or o1 == 127 or o1 >= 224:
        return False
    if o1 == 10:
        return False
    if o1 == 172 and 16 <= o2 <= 31:
        return False
    if o1 == 192 and o2 == 168:
        return False
    if o1 == 169 and o2 == 254:
        return False
    return True


def _extract_ipv4_from_response(body_text: str) -> str | None:
    """Extract valid public IPv4 address from JSON or raw text response."""
    if not body_text:
        return None

    # Try JSON keys first (ip, query)
    try:
        data = json.loads(body_text)
        if isinstance(data, dict):
            for key in ("ip", "query", "ip_address"):
                val = data.get(key)
                if isinstance(val, str) and _is_valid_public_ipv4(val.strip()):
                    return val.strip()
    except Exception:
        pass

    # Fallback to regex scanning anywhere in raw text
    matches = _IPV4_REGEX.findall(body_text)
    for match in matches:
        if _is_valid_public_ipv4(match):
            return match
    return None


def _fetch_public_ip(
    timeout: float = _HTTP_TIMEOUT,
    max_providers: int | None = None,
    retries: int = 2,
) -> str | None:
    """Return the current public IPv4 address, or None if all providers fail.

    Tries each provider with retries. Hardened to parse JSON & text
    responses and filter out IPv6/private IPs.

    ``timeout`` bounds each HTTP request; ``max_providers`` caps how many of
    ``_IP_PROVIDERS`` are tried; ``retries`` is the per-provider retry count.
    Callers that must not block long (e.g. the Shoonya IP guard) pass tighter
    bounds — defaults keep the full hardened chain.
    """
    max_retries_per_provider = retries
    providers = _IP_PROVIDERS if max_providers is None else _IP_PROVIDERS[:max_providers]
    last_error: str | None = None
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) NSEBOT/1.0",
        "Accept": "application/json, text/plain, */*",
    }

    for url in providers:
        for attempt in range(1, max_retries_per_provider + 1):
            try:
                req = urllib.request.Request(url, headers=headers)
                with urllib.request.urlopen(req, timeout=timeout) as resp:
                    raw_bytes = resp.read()
                    body_text = raw_bytes.decode("utf-8", errors="replace").strip()

                ip = _extract_ipv4_from_response(body_text)
                if ip:
                    return ip
                else:
                    raise ValueError(f"No valid public IPv4 address found in response: {body_text[:100]}")
            except Exception as e:
                last_error = str(e)
                log.debug(
                    "IP provider %s failed (attempt %d/%d): %s",
                    url, attempt, max_retries_per_provider, last_error,
                )
                if attempt < max_retries_per_provider:
                    time.sleep(attempt)
                continue

    log.warning("All IP providers failed after retries; last error: %s", last_error or "unknown")
    return None


def _load_stored_ip() -> str | None:
    """Read the last known IP from the state file."""
    try:
        if IP_STATE_PATH.exists():
            data = json.loads(IP_STATE_PATH.read_text(encoding="utf-8"))
            ip = data.get("ip")
            if isinstance(ip, str) and _is_valid_public_ipv4(ip.strip()):
                return ip.strip()
    except Exception as exc:
        log.debug("Could not read stored IP: %s", exc)
    return None


def _save_ip(ip: str) -> None:
    """Persist the current IP to the state file."""
    try:
        IP_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        data = {"ip": ip, "last_checked": time.strftime("%Y-%m-%dT%H:%M:%S%z")}
        IP_STATE_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except Exception as exc:
        log.warning("Failed to save IP state: %s", exc)


def check_ip_changed() -> tuple[str, str] | None:
    """
    Compare current public IP against the last known value.

    Returns:
        (old_ip, new_ip) if the IP has changed since last check.
        None if the IP is unchanged, or if detection failed.
    """
    current_ip = _fetch_public_ip()
    if not current_ip:
        log.warning("IP check skipped — could not determine current public IP")
        return None

    previous_ip = _load_stored_ip()

    # First run — no previous IP to compare, just store and return None.
    if previous_ip is None:
        log.info("Initial IP recorded: %s", current_ip)
        _save_ip(current_ip)
        return None

    if current_ip == previous_ip:
        log.debug("IP unchanged: %s", current_ip)
        return None

    # IP changed!
    log.info("IP changed: %s → %s", previous_ip, current_ip)
    _save_ip(current_ip)
    return (previous_ip, current_ip)

