"""
ISP IP Address Monitor.

Tracks the local machine's public (ISP) IP address and detects changes.
Stores last known IP in data/ip_state.json. Alerts are generated by the
caller (pipeline) via send_text() when a change is detected.

IP detection uses ipify.org as primary source with a simple fallback chain.
"""

from __future__ import annotations

import json
import logging
import time
import urllib.request
from pathlib import Path

from config.settings import DATA_DIR

log = logging.getLogger(__name__)

IP_STATE_PATH = DATA_DIR / "ip_state.json"

# Ordered list of IP detection URLs (primary → fallback).
# Each must return a JSON body with an "ip" key at the top level.
_IP_PROVIDERS = [
    "https://api.ipify.org?format=json",
    "https://api.myip.com",
    "https://ip-api.com/json/",
]

_HTTP_TIMEOUT = 10  # seconds per request


def _fetch_public_ip() -> str | None:
    """Return the current public IP address, or None if all providers fail.

    BUG-H12 FIX: Added retry logic with exponential backoff per provider.
    Previously tried each provider only once, so a transient network blip
    across all 3 providers would skip the IP check entirely for that cycle.
    Now retries each provider up to 2 times with 1s/2s backoff.
    """
    max_retries_per_provider = 2
    last_error: str | None = None
    for url in _IP_PROVIDERS:
        for attempt in range(1, max_retries_per_provider + 1):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "NSEBOT/1.0"})
                with urllib.request.urlopen(req, timeout=_HTTP_TIMEOUT) as resp:
                    data = json.loads(resp.read().decode("utf-8", errors="replace"))
                ip = data.get("ip")
                if ip and isinstance(ip, str) and ip.strip():
                    return ip.strip()
            except Exception as e:
                last_error = str(e)
                log.debug(
                    "IP provider %s failed (attempt %d/%d): %s",
                    url, attempt, max_retries_per_provider, last_error,
                )
                if attempt < max_retries_per_provider:
                    time.sleep(attempt)  # 1s, 2s backoff
                continue
    log.warning("All IP providers failed after retries; last error: %s", last_error or "unknown")
    return None


def _load_stored_ip() -> str | None:
    """Read the last known IP from the state file."""
    try:
        if IP_STATE_PATH.exists():
            data = json.loads(IP_STATE_PATH.read_text(encoding="utf-8"))
            return data.get("ip")
    except Exception as exc:
        log.debug("Could not read stored IP: %s", exc)
    return None


def _save_ip(ip: str) -> None:
    """Persist the current IP to the state file."""
    try:
        IP_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        data = {"ip": ip, "last_checked": time.strftime("%Y-%m-%dT%H:%M:%S%z")}
        IP_STATE_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except Exception as exc:
        log.warning("Failed to save IP state: %s", exc)


def check_ip_changed() -> tuple[str, str] | None:
    """
    Compare current public IP against the last known value.

    Returns:
        (old_ip, new_ip) if the IP has changed since last check.
        None if the IP is unchanged, or if detection failed.
    """
    current_ip = _fetch_public_ip()
    if not current_ip:
        log.warning("IP check skipped — could not determine current public IP")
        return None

    previous_ip = _load_stored_ip()

    # First run — no previous IP to compare, just store and return None.
    if previous_ip is None:
        log.info("Initial IP recorded: %s", current_ip)
        _save_ip(current_ip)
        return None

    if current_ip == previous_ip:
        log.debug("IP unchanged: %s", current_ip)
        return None

    # IP changed!
    log.info("IP changed: %s → %s", previous_ip, current_ip)
    _save_ip(current_ip)
    return (previous_ip, current_ip)
